# Generated by Django 4.2.3 on 2023-07-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemanagement', '0004_alter_documentation_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='documentation',
            field=models.FileField(upload_to='documentations/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
