# Generated by Django 4.2.3 on 2023-07-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='documenationfile',
            new_name='documentation',
        ),
    ]
