# Generated by Django 4.2.3 on 2023-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemanagement', '0003_alter_documentation_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='documentation',
            field=models.FileField(upload_to='movemanagement/documentations/'),
        ),
    ]
